"""add notebook revision table

Revision ID: 27de6f56da90
Revises: 5d464f430f43
Create Date: 2025-03-05 20:42:04.375660+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27de6f56da90'
down_revision = '5d464f430f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_notebook_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_notebook_path', sa.Text(), nullable=False),
    sa.Column('master_notebook_content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_notebook_path', 'assignment_id')
    )
    op.create_index(op.f('ix_master_notebook_revision_id'), 'master_notebook_revision', ['id'], unique=False)
    op.add_column('assignment', sa.Column('master_notebook_revision_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'master_notebook_revision', ['master_notebook_revision_id'], ['id'])
    op.drop_column('assignment', 'master_notebook_path')
    op.alter_column('job_status', 'status_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('submission', sa.Column('master_notebook_revision_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submission', 'master_notebook_revision', ['master_notebook_revision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_column('submission', 'master_notebook_revision_id')
    op.alter_column('job_status', 'status_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('assignment', sa.Column('master_notebook_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'master_notebook_revision_id')
    op.drop_index(op.f('ix_master_notebook_revision_id'), table_name='master_notebook_revision')
    op.drop_table('master_notebook_revision')
    # ### end Alembic commands ###
