"""add job logging table

Revision ID: 5d464f430f43
Revises: bdf5e21a88df
Create Date: 2024-11-11 19:04:46.977449+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d464f430f43'
down_revision = 'bdf5e21a88df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status',
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'STARTED', 'RETRY', 'FAILURE', 'SUCCESS', 'REVOKED', name='jobstatus'), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('status_date', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_job_status_internal_id'), 'job_status', ['internal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_status_internal_id'), table_name='job_status')
    op.drop_table('job_status')
    op.execute(sa.text('DROP TYPE jobstatus'))
    # ### end Alembic commands ###
